'use strict';self.Module={onRuntimeInitialized:function(){onWasmLoaded()}};void 0!=self.importScripts&&(self.importScripts("common.js"),self.importScripts("libwasm.js"));
function Decoder(){this.logger=new Logger("Decoder");this.coreLogLevel=g_nLogLv_Default;this.accurateSeek=!0;this.wasmLoaded=!1;this.tmpReqQue=[];this.decodeInfoCallback=this.requestCallback=this.audioCallback=this.videoCallback=this.decodeTimer=this.cacheBuffer=null;this.intervalDec=g_nIntervalDec_Default;this.m_tDataFullSendNext=Date.now();this.m_tDataMoreSendNext=Date.now();this.m_bDataFinished=!1}
Decoder.prototype.startDecoder=function(a,c,b,e,d,f){if(d){this.coreLogLevel=e||g_nLogLv_Default;d=intArrayFromString(d).concat(0);e=Module._malloc(d.length);Module.HEAPU8.set(d,e);var g=intArrayFromString(f).concat(0);f=Module._malloc(g.length);Module.HEAPU8.set(g,f);c=Module._fnInitDecoder(this.coreLogLevel,c,this.videoCallback,this.audioCallback,this.requestCallback,this.decodeInfoCallback,e,d.length,f,g.length);0==c&&(null==this.cacheBuffer&&(this.cacheBuffer=Module._malloc(a)),this.intervalDec=
b||g_nIntervalDec_Default,this.startDecoding(this.intervalDec),this.m_bDataFinished=!1);Module._free(e);Module._free(f);self.postMessage({t:kRsp_DecoderStart,e:c})}};Decoder.prototype.uninitDecoder=function(){let a=Module._fnUninitDecoder();this.logger.logInfo("Uninit ffmpeg decoder return "+a+".");null!=this.cacheBuffer&&(Module._free(this.cacheBuffer),this.cacheBuffer=null)};
Decoder.prototype.stopDecoder=function(){this.logger.logInfo("closeDecoder.");this.uninitDecoder();this.decodeTimer&&(clearInterval(this.decodeTimer),this.decodeTimer=null,this.logger.logInfo("Decode timer stopped."));self.postMessage({t:kRsp_DecoderStop,e:0})};Decoder.prototype.startDecoding=function(a){this.decodeTimer&&clearInterval(this.decodeTimer);this.decodeTimer=setInterval(this.decode,a);self.postMessage({t:kRsp_DecoderResume,e:0})};
Decoder.prototype.pauseDecoding=function(){this.decodeTimer&&(clearInterval(this.decodeTimer),this.decodeTimer=null);self.postMessage({t:kRsp_DecoderPause,e:0})};
Decoder.prototype.decode=function(){let a=0;for(;5>a++;){var c=Module._fnDecoderOnePacket();if(-107==c){self.decoder.logger.logInfo("Decoder finished.");self.decoder.pauseDecoding();self.postMessage({t:kFinishedEvt});break}for(;-109==c;)c=Module._fnDecodeOnePacket();c=Module._fnGetDurationOfPktList();2E3>c&&self.decoder.m_tDataMoreSendNext<Date.now()&&(self.decoder.m_bDataFinished&&0>=c?(self.decoder.logger.logInfo("Decoder finished."),self.decoder.pauseDecoding(),self.postMessage({t:kFinishedEvt})):
(self.postMessage({t:kDecoderDataMore}),self.decoder.m_tDataMoreSendNext=Date.now()+1E3))}};
Decoder.prototype.sendData=function(a){if(a&&0!=a.byteLength){a=new Uint8Array(a);Module.HEAPU8.set(a,this.cacheBuffer);a=Module._fnSendData(2,this.cacheBuffer,a.length);if(0>a)if(-112==a)self.postMessage({t:kReauth});else{-111==a?(self.decoder.logger.logError("Error of your authorization, please contact us and get a new one."),self.postMessage({t:kAuthErr})):self.decoder.logger.logError("Decoder sendData Error.");self.decoder.pauseDecoding();self.postMessage({t:kFinishedEvt});return}3E4<Module._fnGetDurationOfPktList()&&
this.m_tDataFullSendNext<Date.now()&&(self.postMessage({t:kDecoderDataFull}),this.m_tDataFullSendNext=Date.now()+2E3)}};Decoder.prototype.seedKeyData=function(a,c){if(c){c=intArrayFromString(c).concat(0);var b=Module._malloc(c.length+1);Module.HEAPU8.set(c,b);Module._fnSendData(a,b,c.length);Module._free(b)}};Decoder.prototype.seekTo=function(a){a=Module._seekTo(a,this.accurateSeek?1:0);self.postMessage({t:kRsp_DecoderSeekTo,r:a})};
Decoder.prototype.processReq=function(a){switch(a.t){case kReq_DecoderStart:this.startDecoder(a.c,a.i,a.v,a.l,a.k,a.u);break;case kReq_DecoderStop:this.stopDecoder();break;case kReq_DecoderResume:this.startDecoding(a.i);break;case kReq_DecoderPause:this.pauseDecoding();break;case kFeedData:this.sendData(a.d);break;case kReq_DecoderSeekTo:this.seekTo(a.ms);break;case kDataFinished:this.m_bDataFinished=!0;break;case kRsp_DownloadStart:this.seedKeyData(0,a.u);break;case kReq_Auth:this.seedKeyData(1,
a.a);break;case kReq_Profile:this.seedKeyData(0,a.u);break;case kReq_domain:this.seedKeyData(0,a.u);break;case kReq_uuid:this.seedKeyData(0,a.u);break;default:this.logger.logError("Unsupport messsage "+a.t)}};Decoder.prototype.cacheReq=function(a){a&&this.tmpReqQue.push(a)};
Decoder.prototype.onWasmLoaded=function(){this.logger.logInfo("Wasm loaded.");this.wasmLoaded=!0;this.getVersion();this.videoCallback=Module.addFunction(function(a,c,b,e,d,f,g){a=Module.HEAPU8.subarray(a,a+c);a=new Uint8Array(a);b={t:kVideoFrame,s:b,d:a,w:e,h:d,y:f,u:g};self.postMessage(b,[b.d.buffer])},"viiiiiii");this.audioCallback=Module.addFunction(function(a,c,b){self.decoder.wasmLoaded&&(a=Module.HEAPU8.subarray(a,a+c),a=new Uint8Array(a),b={t:kAudioFrame,s:b,d:a},self.postMessage(b,[b.d.buffer]))},
"viii");this.aiCallback=Module.addFunction(function(a,c,b,e,d,f){a=Module.HEAPU8.subarray(d,d+f);a=new Uint8Array(a);c={t:kAiFrame,s:c,w:b,h:e,d:a};self.postMessage(c,[c.d.buffer])},"viiiiii");this.requestCallback=Module.addFunction(function(a,c){self.postMessage({t:kRequestDataEvt,o:a,a:c})},"vii");for(this.decodeInfoCallback=Module.addFunction(function(a,c,b){switch(a){case 1:if(4>b)break;a=c>>2;b=Module.HEAP32.subarray(a,a+b);self.postMessage({t:kVideoInfo,e:0,v:{d:b[0],p:b[1],w:b[2],h:b[3]}});
break;case 2:if(4>b)break;a=c>>2;b=Module.HEAP32.subarray(a,a+b);self.postMessage({t:kAudioInfo,e:0,a:{f:b[1],c:b[2],r:b[3],s:b[0]}});break;case 3:0<b?(a=Module.HEAPU8.subarray(c,c+b),a=new Uint8Array(a),b={t:kWriteFrame,d:a,l:b},self.postMessage(b,[b.d.buffer])):self.postMessage({t:kWriteFrame,l:0});break;case -1:self.postMessage({t:kRsp_DecoderStart,e:-1})}},"viii");0<this.tmpReqQue.length;){let a=this.tmpReqQue.shift();this.processReq(a)}};self.decoder=new Decoder;
Decoder.prototype.getVersion=function(){let a=Module._malloc(128);try{let c=Module._fnGetVersion(a,128),b=Module.HEAPU8.subarray(a,a+c),e="";for(let d=0;d<c;++d)e+=String.fromCharCode(b[d]);Module._free(a);self.postMessage({t:kVersion,v:e})}finally{Module._free(a)}};self.onmessage=function(a){self.decoder?(a=a.data,self.decoder.wasmLoaded?self.decoder.processReq(a):(self.decoder.cacheReq(a),self.decoder.logger.logInfo("Temp cache req "+a.t+"."))):console.log("[ER] Decoder not initialized!")};
function onWasmLoaded(){if(self.decoder)self.decoder.onWasmLoaded();else console.log("[ER] No decoder!")};