'use strict';function LoaderHLS(){this.szUrlHls=this.szUrlMain=null;this.listM3u8=[];this.listTs=[];this.szUrlHeader=this.szTsHeader=null;this.nIndexM3u8=this.nIndexTs_Sign=this.nIndexTs=0;this.bIsStream=!0;this.szUrlTsLast=null;this.fDuration=this.fDurationSecs=0;this.XmlHttp=this.fetchController=this.FetchHttp=null;this.nUrlType=HLS_URL_TYPE_HLS;this.bRequesting=!1;this.nTimeout=g_nTimeout_Default;this.nTimeoutCount=0;this.timerRequest=null;this.nIntervalRequest=g_nInterval_Default;this.bFirstTime=
!0}LoaderHLS.prototype.fnParseLine=function(a,b){let c=[],d=a.indexOf(b),g;for(;-1!=d;)g=a.indexOf(b,d+1),-1==g?c.push(a.substring(d)):c.push(a.substring(d,g)),d=g;return c};
LoaderHLS.prototype.fnCallBack=function(a,b){a=this.fnParseLine(a,"#");let c=[],d=[],g=0;let n=/.m3u8/,p=/^#EXT-X-TARGETDURATION/,q=/^#EXTINF/,r=/^#EXT-X-STREAM-INF/,t=/^http/,u=/#EXTINF:\s*(\d*(?:\.\d+)?)(?:,[^\r\n]*[\r\n\s]+)?([^\r\n]*)(?:[\s\r\n]*)?/,v=b.substring(0,b.lastIndexOf("/")+1);let m=this.nIndexTs_Sign;for(let k=0;k<a.length;++k){var e=a[k];if(q.test(e)){var f=e.replace("\r","");/^#EXTINF:?([0-9\.]*)?,?(.*)?$/.exec(f);f=u.exec(e);e=parseFloat(f[1]);var h=f[2];f=!1;for(let l=m;l<this.listTs.length;++l)if(h==
this.listTs[l].f){m=l;f=!0;break}f?0==k&&(this.nIndexTs_Sign=m):(0==k&&(this.nIndexTs_Sign=this.listTs.length),d.push({d:e,f:h}),g+=e)}else if(p.test(e))e=e.split(":"),2==e.length&&(e=parseFloat(e[1]),e>this.fDuration&&(this.fDuration=e,e=parseInt(1E3*e),self.postMessage({t:kRsp_DurationChange,n:e})));else if(r.test(e))for(e=e.split("\n"),f=1;f<e.length;++f)h=e[f],n.test(h)&&(h=t.test(h)?h:v+h,c.push(h))}0<c.length&&(this.listM3u8[0]==b&&this.listM3u8.splice(0,1),this.listM3u8=c.concat(this.listM3u8));
0<d.length&&(this.listTs=this.listTs.concat(d),this.fDurationSecs+=g,this.bFirstTime&&this.bIsStream&&(this.nIndexTs=0,this.bFirstTime=!1));self.postMessage({t:kRsp_FileTimeLength,d:this.fDurationSecs})};LoaderHLS.prototype.fnStartTimer=function(){let a=this;this.timerRequest=setInterval(function(){a.fnOnRequest()},this.nIntervalRequest)};LoaderHLS.prototype.fnStopTimer=function(){null!=this.timerRequest&&(clearInterval(this.timerRequest),this.timerRequest=null)};
LoaderHLS.prototype.fnOnRequest=function(){this.nLastRecvTime>Date.now()+5E3&&this.postMessage({t:kCommonRsp,r:EE_Err_Loader_Timeout});this.bRequesting||(0<this.listTs.length&&this.nIndexTs<this.listTs.length?this.fnRequest(this.listTs[this.nIndexTs].f,HLS_URL_TYPE_TS)==EE_Loader_OK&&(++this.nIndexTs,this.nUrlType=HLS_URL_TYPE_TS):!this.bIsStream&&0<this.listTs.length?(self.postMessage({t:kUriDataFinished}),this.fnPause()):0<this.listM3u8.length?(this.nIndexM3u8>=this.listM3u8.length&&(this.nIndexM3u8=
0),this.fnRequest(this.listM3u8[this.nIndexM3u8],HLS_URL_TYPE_HLS)==EE_Loader_OK&&(++this.nIndexM3u8,this.nUrlType=HLS_URL_TYPE_HLS)):(this.fnRequest(this.szUrlHls,HLS_URL_TYPE_HLS),this.nUrlType=HLS_URL_TYPE_HLS))};
LoaderHLS.prototype.fnRequestM3u8=function(a){let b=this.XmlHttp=this.fnCreateCORS("Get",a),c=this;b.ontimeout=function(){++c.nTimeoutCount;c.nTimeoutCount>g_nTimeoutCount_Max&&self.postMessage({t:kUriDataError,r:EE_Err_Loader_Timeout})};b.onreadystatechange=function(){b.readyState===XMLHttpRequest.DONE&&(200===b.status?c.fnCallBack(b.response,a):self.postMessage({t:kUriDataError,r:EE_Err_Loader_Net}),c.bRequesting=!1)};b.onerror=function(){self.postMessage({t:kUriDataCors,r:Error_Url_CORS})};b.responseType=
HLS_URL_TYPE_HLS==HLS_URL_TYPE_TS?"arraybuffer":"text";let d=a.indexOf("://");this.szUrlHeader=a.substring(0,a.indexOf("/",0>d?0:d+3));this.szTsHeader=a.substring(0,a.lastIndexOf("/")+1);this.bRequesting=!0;b.timeout=this.nTimeout;b.send();return EE_Loader_OK};function tenToSixteen(a){a=a.toString(16);return"0x"+"00000000".substr(0,8-a.length)+a}function tenToBinary(a){a=a.toString(2);return"00000000".substr(0,8-a.length)+a}
LoaderHLS.prototype.fnCreateCORS=function(a,b){null==this.XmlHttp?this.XmlHttp=new XMLHttpRequest:this.XmlHttp.abort();let c=this.XmlHttp;"withCredentials"in c?c.open(a,b,!0):"undefined"!=typeof XDomainRequest?(new XDomainRequest).open(a,b):c=null;return c};
LoaderHLS.prototype.fnRequestTs=function(a){let b=a;/^http/.test(a)||(b="/"==a.charAt(0)?this.szUrlHeader+a:this.szTsHeader+a);let c=this,d=this.fnCreateCORS("GET",b);d&&(d.responseType="arraybuffer",d.ontimeout=function(){++c.nTimeoutCount;3<c.nTimeoutCount&&self.postMessage({t:kUriDataError,r:EE_Err_Loader_Timeout});--c.nIndexTs;c.bRequesting=!1;console.log("ontimeout:"+c.nIndexTs)},d.onreadystatechange=function(){d.readyState===XMLHttpRequest.DONE&&(200===d.status?downloader.reportData(d.response):
self.postMessage({t:kUriDataError,r:EE_Err_Loader_Net}),c.bRequesting=!1)},d.responseType="arraybuffer",this.bRequesting=!0,d.timeout=this.nTimeout,d.send(),this.szUrlTsLast=b);return EE_Loader_OK};LoaderHLS.prototype.fnRequest=function(a,b){if(null==a)return Error_Loader_Param;if(this.bRequesting)return Error_Loader_Busy;switch(b){case HLS_URL_TYPE_HLS:return this.fnRequestM3u8(a);case HLS_URL_TYPE_TS:return this.fnRequestTs(a)}return Error_Loader_Param};
LoaderHLS.prototype.fnInit=function(a,b,c){if(null==a)return Error_Loader_Param;this.bIsStream=b;this.szUrlMain=a.substring(0,a.lastIndexOf("/")+1);this.szUrlHls=a;this.nTimeout=c||g_nTimeout_Default;this.bFirstTime=!0;return EE_Loader_OK};LoaderHLS.prototype.fnStart=function(){this.fnStartTimer();this.nLastRecvTime=Date.now()};LoaderHLS.prototype.fnPause=function(){this.fnStopTimer()};
LoaderHLS.prototype.fnDestory=function(){this.fnStopTimer();this.szUrlHls=this.szUrlMain=null;this.listM3u8=[];this.listTs=[];this.szUrlHeader=this.szTsHeader=null;this.nIndexM3u8=this.nIndexTs_Sign=this.nIndexTs=0;this.bIsStream=!0;this.szUrlTsLast=null;this.fDuration=0;this.timerRequest=null;this.bFirstTime=!0;this.optBackSkip=!1;this.fDurationSecs=0;this.fetchController&&(this.fetchController.abort(),this.fetchController=null);this.FetchHttp=null;this.XmlHttp&&(this.XmlHttp.abort(),this.XmlHttp=
null);this.nUrlType=HLS_URL_TYPE_HLS;this.bRequesting=!1;this.nTimeout=g_nTimeout_Default;this.nTimeoutCount=0;this.nIntervalRequest=g_nInterval_Default};LoaderHLS.prototype.fnJumpTime=function(a){let b=0,c=a.index;a=b.streamType;if(kProtoType_HTTP_M3U8==a){let d=0;b=this.listTs.findIndex(g=>{d+=g.d;return d>c});console.log("=======\u65f6\u95f4\u8df3\u8f6c==ts==\u5e8f\u53f7====",b)}else kProtoType_HTTP==a&&(b=0);this.bIsStream=!1;this.nIndexTs=b;this.fnStartTimer()};